name: Pre Release

on:
  push:
    branches:
      - fast

jobs:
  build:
    name: Ubuntu Latest Build
    permissions:
      contents: write
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21,    # Current Java LTS
        ]
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'oracle'

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pre_release_branches: "fast"
          custom_release_rules: "fix:prerelease,feat:prerelease"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Change version in `gradle.properties`
        run: python .github/change_version.py ${{ steps.tag_version.outputs.new_tag }}

      - name: Set git user
        uses: fregante/setup-git-user@v2

      - name: Check for changes
        run: git status

      - name: Stage changed files
        run: git add *

      - name: Commit changed files
        run: "git commit -m 'Action: Update version in `gradle.properties`'"

#      - name: Set remote url
#        run: git remote set-url origin https://T2PeNBiX99wcoxKv3A4g:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Fetch from fast
        run: git fetch origin fast

      - name: Push code to fast
        run: git push origin fast

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        if: ${{ matrix.java == '21' }} # Only upload artifacts built from latest java
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
  
  upload:
    name: Create Pre Release
    permissions:
      contents: write
    needs: [ windows-release-build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4

#      - name: Bump version and push tag
#        id: tag_version
#        uses: mathieudutour/github-tag-action@v6.2
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          pre_release_branches: "fast"
#          custom_release_rules: "fix:prerelease,feat:prerelease"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Artifacts/polymer-server-utils-*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.build.outputs.new_tag }}
          name: Pre Release ${{ needs.build.outputs.new_tag }}
          body: ${{ needs.build.outputs.changelog }}
          prerelease: true